//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int C_ID { get; set; }
        public string C_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string MOBILE_NUMBER { get; set; }
        public string ADDRESS { get; set; }
    }
}
