//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int ROUTE_ID { get; set; }
        public string START_LOCATION { get; set; }
        public string END_LOCATION { get; set; }
        public decimal DISTANCE { get; set; }
    }
}
