//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int SCHEDULE_ID { get; set; }
        public Nullable<int> BUS_ID { get; set; }
        public Nullable<int> ROUTE_ID { get; set; }
        public System.DateTime DEPARTURE_TIME { get; set; }
        public System.DateTime ARRIVAL_TIME { get; set; }
    }
}
